[package]
name = "bgpkit-broker"
version = "0.6.2"
edition = "2018"
authors = ["Mingwei Zhang <mingwei@bgpkit.com>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/bgpkit/bgpkit-broker"
documentation = "https://docs.rs/bgpkit-broker"
description = """
A library to access BGPKIT Broker API and enable searching for BGP data archive files over time from public available
data sources.
"""
keywords = ["bgp", "bgpkit", "api"]

[[bin]]
path= "src/cli/broker.rs"
name="bgpkit-broker"
required-features = ["cli"]

[dependencies]
thiserror = "1.0"
chrono = { version = "0.4", features = ["serde"] }
log="0.4"
reqwest = {version = "0.11.17", features = ["blocking", "json"]}
serde={version="1", features = ["derive"]}
serde_json = "1"
tracing = "0.1"

# crawler dependencies
regex = { version = "1", optional = true }
scraper = { version = "0.16", optional = true }
tokio = {version="1", optional = true, features = ["full"] }
futures = {version="0.3", optional = true}
duckdb = {version="0.8", optional = true, features = ["bundled", "parquet", "httpfs", "r2d2"]}
r2d2 = {version="0.8", optional = true}
oneio = {version="0.11.0", optional = true}

# binary cli dependencies
clap = {version= "4.3", features=["derive"], optional=true}
num_cpus = {version="1.15", optional=true}
tracing-subscriber = {version="0.3", optional=true}
config = {version = "0.13.1", features = ["toml"], optional=true}
dirs = {version="5", optional=true}
humantime = {version="2.1", optional = true}

[features]
default=["crawler", "cli", "db"]
crawler = ["regex", "scraper", "tokio", "futures", "oneio"]
db = ["duckdb", "r2d2"]
cli = ["clap", "num_cpus", "tracing-subscriber", "config", "dirs", "humantime"]

[dev-dependencies]
tracing-subscriber = "0.3.17"