[package]
name = "bgpkit-broker"
version = "0.6.0"
edition = "2018"
authors = ["Mingwei Zhang <mingwei@bgpkit.com>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/bgpkit/bgpkit-broker"
documentation = "https://docs.rs/bgpkit-broker"
description = """
A library to access BGPKIT Broker API and enable searching for BGP data archive files over time from public available
data sources.
"""
keywords = ["bgp", "bgpkit", "api"]

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
log="0.4"
reqwest = {version = "0.11.17", features = ["blocking", "json"]}
serde={version="1", features = ["derive"]}
serde_json = "1"

[dev-dependencies]
anyhow = "1.0"